server:
  port: 8080

#  eureka.client.register-with-eureka=true
#  eureka.client.fetch-registry=true
#  eureka.client.serviceUrl.defaultZone=http://localhost:8763/eureka/
#  instance.hostname=localhost

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8763/eureka/

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: designpattern
          uri: http://localhost:8001/dp/composite/
          predicates:
            - Path=/dp/composite/**